//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM01_520_Rekhviashvili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventss
    {
        public string ID { get; set; }
        public string Event { get; set; }
        public string Date { get; set; }
        public string Days { get; set; }
        public string City { get; set; }
    }
}
